export { ButtonSlider as ComponentButtonSlider } from "./ButtonSlider"
export { TitleSlider as ComponentTitleSlider } from "./TitleSlider"
export { ListMarker as ComponentListMarker } from "./ListMarker"
export {ButtonInterface as ComponentButtonInterface} from "./ButtonInterface"
export { ButtonTakePicture as ComponentButtonTakePicture} from "./ButtonTaePicture"
export { Loading as ComponentLoading} from "./Loading"